// pipeline {
//     agent any
//     environment {
//         MAVEN_HOME = "/opt/apache-maven-3.9.0"
//         PATH = "$MAVEN_HOME/bin:$PATH"
//     }
//     stages {
//         stage('Build') {
//             steps {
//                 sh 'mvn -B -DskipTests clean package'
//             }
//         }
//         stage('Test') {
//             steps {
//                 sh 'mvn test'
//             }
//             post {
//                 always {
//                     junit 'target/surefire-reports/*.xml'
//                 }
//             }
//         }
//         stage('Deliver') {
//             steps {
//                 sh './jenkins/scripts/deliver.sh'
//             }
//         }
//         stage('Complete') {
//             steps {
//                 echo 'Job complete'
//             }
//         }
//     }
// }
pipeline {
    agent any

    parameters {
        booleanParam(defaultValue: false, description: "Enable service?", 
        name: "myBoolean")
        string(defaultValue: "TEST", description: "which env to deploy in?", 
        name: "deployEnv")
    }

    stages {
        stage("Demo") {
            steps {
                echo "booleanParam is set to: ${params.myBoolean}"
                echo "string is set to: ${params.deployEnv}"

            }
        }
    }
}
